version: '3.8'

services:
  db:
    image: postgres:15
    container_name: url_shortener_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:latest
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url_shortener_app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:

